[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "systeccan"
version = "0.0.0"
description = "SYSTEC CAN adapter driver wrapper"
readme = "README.rst"
